

name: maven

on:
  pull_request:
    branches: [main]

jobs:
  run-test:
    name: 'Run tests'
    runs-on: ubuntu-latest

    steps:
      - name: Git clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'

      - name: Attach screenshots and reports
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: screenshots-and-report
          path: |
            screenshots
            target/surefire-reports/emailable-report.html

